from fonctions.module import *
from fonctions.fonction import *



lire_et_ecrire_csv(test_E1, test_S1, [1])
lire_et_ecrire_csv(test_E2, test_S2, [1])
lire_et_ecrire_csv(test_E3, test_S3, [1])
lire_et_ecrire_csv(test_E4, test_S4, [1])
ecriture_csv(test_S5, header_S5, data_S5)
ecriture_csv(test_S6, header_S6, data_S6)
ecriture_csv(test_S7, header_S7, data_S7)
ecriture_csv(test_S8, header_S8, data_S8)
lire_et_ecrire_csv(test_E9, test_S9, [1])
lire_et_ecrire_csv(test_E10, test_S10, [1])
lire_et_ecrire_csv(test_E11, test_S11, [1])
lire_et_ecrire_csv(test_E12, test_S12, [1])

print("--------  Data 1  ------------")
lecture_csv(test_S1)
print("--------  Data 2  ------------")
lecture_csv(test_S2)
print("--------  Data 3  ------------")
lecture_csv(test_S3)
print("--------  Data 4  ------------")
lecture_csv(test_S4)
print("--------  Data 5  ------------")
lecture_csv(test_S5)
print("--------  Data 6  ------------")
lecture_csv(test_S6)
print("--------  Data 7  ------------")
lecture_csv(test_S7)
print("--------  Data 8  ------------")
lecture_csv(test_S8)
print("--------  Data 9  ------------")
lecture_csv(test_S9)
print("--------  Data 10  ------------")
lecture_csv(test_S10)
print("--------  Data 11  ------------")
lecture_csv(test_S11)
print("--------  Data 12  ------------")
lecture_csv(test_S12)
